### ISSUE TITLE
Clarification on using lib carpentry materials outside of workshops

### ISSUE THREAD

**Issue by arieldeardorff** [LibraryCarpentry/lc-overview#12]
Something that seems to be missing from the Library Carpentry overview page is a sentence or two about how carpentry materials and lessons are freely available with a creative commons license and can therefore be used in other kinds of workshops or classes as well as via the more formal Lib Carpentry workshop model. For example if I wanted to use part of the Open Refine curriculum in a class I am teaching and not call it a Library Carpentry workshop. To me it seems like people interested in these materials have three ways to engage: host a formal library carpentry, host a hybrid/self-organized library carpentry, and use/modify carpentry materials in their own workshops/classes (with attribution but without calling them "library carpentry workshops"). Is that accurate?

**Comment by libcce** [comment]
Hi @arieldeardorff thanks again for the suggestion. I added language to https://librarycarpentry.org/lessons/ and https://librarycarpentry.org/lc-overview/, What do you think?

**Comment by arieldeardorff** [comment]
I think that works. Thanks!
