### ISSUE TITLE
Images not centered on file naming and computation approach episodes

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-overview#15]
- https://librarycarpentry.org/lc-overview/06-file-naming-formatting/index.html
- https://librarycarpentry.org/lc-overview/04-computational-approach/index.html

**Comment by ccronje** [comment]
This one has me scratching my head @libcce, I had a look locally but couldn't spot the problem.

Also left-aligned is image under **The Strategic Value of Library Carpentry & The Carpentries to Research Libraries** in https://librarycarpentry.org/lc-overview/02-intro-to-library-carpentry/index.html

**Comment by libcce** [comment]
I wonder if it’s because the template/styles haven’t been updated @ccronje ? Wonder if @cmacdonell can help here?

**Comment by libcce** [comment]
@fmichonneau do you know why the images are not centered? Example here https://librarycarpentry.org/lc-overview/04-computational-approach/index.html.

**Comment by morskyjezek** [comment]
I think this is also true on the introduction page (there most of the images are quite large, but the smaller ones are likewise left justified.

**Comment by morskyjezek** [comment]
Given the upcoming transition to the new styles template, either this will be resolved in the new format or it will need a new issue, so I'm closing this issue. Thanks all for your contributions and suggestions!
