### ISSUE TITLE
Updated workshops template

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-overview#16]
Updated workshops template to reflect LC Workshop Overview and Introduction to Working with Data changes, see:

- https://github.com/carpentries/workshop-template/pull/620
- https://github.com/carpentries/workshop-template/pull/619

Review + close when PRs merged

**Comment by ccronje** [comment]
Thanks @libcce I've left reviews on both PRs

**Comment by ccronje** [comment]
@libcce there's a conflict with https://github.com/carpentries/workshop-template/pull/619 - are you able to fix please?

**Comment by libcce** [comment]
@ccronje I fixed the conflict but there is one thing I'm unsure about, the workshop surveys that were added by another PR. I just left them in. Should be fine.
