### ISSUE TITLE
Add new curriculum variants to 'Beyond the Standard Workshop'

### ISSUE THREAD

**Issue by ccronje** [LibraryCarpentry/lc-overview#17]
Add new curriculum variants to 'Beyond the Standard Workshop' in order to pilot / seek feedback from LC community.

Variant Workshops (Menus):
- Intro to Library Carpentry > OpenRefine
Context about how this is a good combination for pilots and workshops connected with conferences and other events...
- Intro to Git > Unix Shell > OpenRefine > SQL
Context about core data analysis...

References:
- https://github.com/LibraryCarpentry/lc-sql/issues/34#issuecomment-458616256
- https://github.com/LibraryCarpentry/governance/issues/16

**Comment by ccronje** [comment]
Future menus as lessons mature https://github.com/LibraryCarpentry/governance/issues/14#issuecomment-509286378

**Comment by ccronje** [comment]
In curricula descriptions, include 'parts' to reinforce flexibility in how they can be taught https://github.com/LibraryCarpentry/governance/issues/15

**Comment by ccronje** [comment]
Hi @PhilReedData, what do you think about adding a new section after Parts vs Days called Curricula to outline the different options? For example:

**Curricula**

Recently, the LC Curriculum Advisory Committee voted to expand the standard workshop offering to include other curriculums. We will be working to include these offerings in [The Carpentries workshop request form](https://amy.carpentries.org/forms/workshop/).

Curriculum | Description | Lesson menu | Total time estimated
-- | -- | -- | --
Library Carpentry Standard Workshop | Core lessons | 1) [Introduction to Working with Data](https://librarycarpentry.org/lc-overview/), 2) [The Unix Shell](https://librarycarpentry.org/lc-shell/), 3) [OpenRefine](https://librarycarpentry.org/lc-open-refine/), 4) [Introduction to Git](https://librarycarpentry.org/lc-git/) | 2 days
Library Carpentry Introduction | A good combination for pilots and workshops connected with conferences and other events | 1) [Introduction to Library Carpentry](https://librarycarpentry.org/lc-overview/02-intro-to-library-carpentry/index.html), 2) [OpenRefine](https://librarycarpentry.org/lc-open-refine/) | Half day
Library Carpentry Data Analysis Core | An introduction to data analysis and good practices including versioning, cleaning, automation, manipulation, and structured queries | 1) [Introduction to Git](https://librarycarpentry.org/lc-git/), 2) [The Unix Shell](https://librarycarpentry.org/lc-shell/), 3) [OpenRefine](https://librarycarpentry.org/lc-open-refine/), 4) [SQL](https://librarycarpentry.org/lc-sql/) | 2 days
Custom | Design your own workshop to suit your local needs | Select from https://librarycarpentry.org/lessons/ | Estimate total time from lesson schedules e.g. https://librarycarpentry.org/lc-shell/

**Comment by PhilReedData** [comment]
Hi @ccronje, that looks great. I think you have covered all the relevant and necessary information in a relatively small space, just what we need.

I had not considered what updates the Carpentries workshop request form might require. Is there more work required for the request form to reflect what we will be advertising with these curricula?

**Comment by libcce** [comment]
@ccronje this looks like a great table 👍 only comment i have is to include "and/or" under the standard lesson menu as well as in parentheses (must include three of the four lessons) or similar. this looks great though! 

@PhilReedData i think once you have this squared away you/Carmi/all CAC members need to write team@carpentries.org, direct them to this curriculum list, and ask how the workshop offerings can be updated via the workshop request form and other related material. Likely, that will be on their end to resolve. The CAC's role is to advise them of a decision (but they may ask you for help with making these changes).

**Comment by ccronje** [comment]
Thanks @PhilReedData @libcce, @libcce I've included your note note in https://github.com/LibraryCarpentry/lc-overview/pull/18 - once the PR is merged I'll send an email to the carpentries team and copy in the CAC.
