### ISSUE TITLE
Link broken in Jargon Busting episode

### ISSUE THREAD

**Issue by arockenberger** [LibraryCarpentry/lc-overview#32]
Hei friends!

In the following file (https://github.com/LibraryCarpentry/lc-overview/edit/gh-pages/_episodes/03-jargon-busting.md) in line 32, the link doesn't return anything in the Twitter search:

[variation between our jargon busting sessions](https://twitter.com/search?q=jargon%20libcarpentry&src=typed_query&f=live)

Remove or edit?

Best,

Annika

**Comment by ppival** [comment]
Can you double-check? It works for me now; I know Twitter Search (all of
Twitter?) was down for a bit...

Paul

**Comment by arockenberger** [comment]
Ha, looks like it works now! Didn't know Twitter was down, that was probably it.
