### ISSUE TITLE
Is this repo necessary? Most content on librarycarpentry.org, no?

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/lc-overview#4]
Aiming for achieving only _one single source of truth_, I wonder whether there is any significant content needed on a separate website, that http://librarycarpentry.org/#portfolioModal4 mustn't contain?

**Comment by libcce** [comment]
Thanks @katrinleinweber, the LC Overview page stems from guidance from @tracykteal's guidance to create a similar overview page for DC's http://www.datacarpentry.org/ecology-workshop/.

**Comment by libcce** [comment]
Thanks! @katrinleinweber this content has been moved to the LC website.
