### ISSUE TITLE
Decommission LC-Overview Lesson

### ISSUE THREAD

**Issue by emcaulay** [LibraryCarpentry/lc-overview#56]
Per decision by LC-CAC on 2023-09-21, the lc-overview lesson will be decommissioned and constituent parts may be provided as content in other parts of the LC or Carpentries documentation. 

This work will be performed by @jt14den and @emcaulay . They will report back to LC-CAC at November 2023 CAC meeting. (I think meeting is 2023-11-16).

**Comment by emcaulay** [comment]
relates to #49 

will be enacted through
#58

**Comment by emcaulay** [comment]
Library Carpentry Curriculum Advisory Committee (LC-CAC) recommended considering the following lesson to replace LC-Overview : https://ucla-data-science-center.github.io/intro-computational-thinking/.

**Comment by emcaulay** [comment]
At the Maintainers Meeting on 2024-03-20, a few of us discussed the value of a start-from-the-very-beginning lesson as part of Library Carpentry.

**Comment by jas58** [comment]
I taught the ucla intro to computational thinking (file link above) yesterday as part of a LC workshop (w/ OpenRefine and SQL).  
I felt Practice 2B was a bit too much to expect of novices, but the responses on the [etherpad](https://pad.carpentries.org/2024-04-02-utah-nnlm-online) also helped advanced students see the range of answers from less advanced students, and novices could see words in-context from the advanced responses.  The Practice 2B solution coded in SQL, which seemed odd for a workshop that would culminate in SQL.

I tried Jargon Busting as an icebreaker and there was a weird anchor bias.  The welcome screen mentioned "Computational Thinking" and someone mentioned Pseudocode.  That became everyone's response, either Computational Thinking or Pseudocode.  Nothing about APIs, or scraping, R/Python, libraries, syntax, etc.  I wonder if a word cloud would be a better start, or a blank screen?

The organizer wanted to skip Tidy Data, though I think that and/or RegEx might go well after computational thinking.

**Comment by morskyjezek** [comment]
That seems like a good point, since that exercise in Practice 2B relies on knowledge of the shell/Bash, which may or may not be taught in a subsequent lesson. It also seems to violate the general lesson design practice of concept mapping, which tries to ensure that all necessary concepts (in this case, shell, unix, rm, command syntax, flags, targets/outputs etc) are introduced in advance. 

@jas58 - what did you use as the reference material for jargon busting? Is that from the decommisioned lesson, or is it in the    new lesson, or somewhere else?

**Comment by morskyjezek** [comment]
Overall, as a contribution to the broader discussion of whether or not to "replace" the decommissioned lesson with the computational thinking lesson. I do like the computation thinking lesson generally as a candidate. That said, there are a few useful things that would no longer be covered at all, including: 

* useful discussion of filenaming
* coverage of keyboard shortcuts
* and the useful references that were in the previous lesson, such as the Data Savvy report, and other useful context for managers and administrators
* another point to me is that this doesn't include any references on where computation thinking has been theorized, for example the articles and work of Mega Subramanian, or this ALA volume: https://www.ala.org/advocacy/sites/ala.org.advocacy/files/content/tools/RtC%20Case%20Studies_FINAL2.pdf 

Note that I'm completely supportive of retiring the old intro lesson, but I guess I'm also wondering if there are any other candidates for an intro lesson.

**Comment by drjwbaker** [comment]
Just chipping in (yes, I still follow this repo) to say that I'm amazed - in a nice way - of how much of our trial workshop 9 years ago survives in the 'Overview' lesson. Glancing back through it without having looked at it in a while, it probably more closely reflects how I work than how other people should be encouraged to work. So yeah, I'm glad it is being retired. That said, I still use that 'jargon busting' exercise (or varients thereof) in a variety of education situations, and always enjoyed that part the most when running LC workshops. Good luck with the refresh!

**Comment by jas58** [comment]
I did not introduce any material before asking for jargon to bust; it was the icebreaker.  So perhaps it doesn't work as an icebreaker, but requires some initial material of some sort.

**Comment by chennesy** [comment]
Thanks @jas58, @drjwbaker  and @morskyjezek! A few of us from LC-CAC are meeting next week to try to close some of these loops. I'll note that LC-CAC already agreed that the Jargon Busting, File naming, and Kybd shortcuts content should all be moved into other core lessons before the LC Overview lesson is retired. 

And we've discussed the possibility of either Tidy Data *or* the Intro to Computational Thinking lesson becoming the recommended Core curriculum intro lesson. (A lot of folks already use Tidy Data to start LC workshops). Any/all opinions on that are welcome!

**Comment by jt14den** [comment]
Thanks @chennesy and @drjwbaker, @jas58, @emcaulay @morskyjezek. We are also interested in "paths" through the curriculum that are recommended b/c we recognize that ppl are teaching different things depending on the audience.  @weaverbel's Intro to Computational Thinking lesson is now in  the LC org here: http://librarycarpentry.org/lc-computational-thinking/. I'll work a pr to add to the website proper.

**Comment by morskyjezek** [comment]
That's a good point about the tidy data as an intro. I think most of the Data or software carpentry sessions I've been to used their variants of that lesson as an intro. 

Thanks short these great discussions! I just want to amplify the sense here that this is a good change, even though it's complex and overdue, so thanks for all of your work on this! It will be a great development for the Library Carpentry community!

**Comment by emcaulay** [comment]
When I taught the jargon-busting episode recently (in 2023), it worked fabulously as an ice breaker. I would say that @jas58 and my conflicting experience matches the feedback I've seen on this repo. "Get rid of it, it's awful" and "I love it, it's a keystone!"

**Comment by chennesy** [comment]
PRs have been made to add Jargon Busting as an optional episode in Tidy Data and Intro to Computational Thinking. See related [comment](https://github.com/LibraryCarpentry/lc-overview/issues/59#issuecomment-2075098014) on issue #59.

**Comment by chennesy** [comment]
Lesson is retired and archived [on Zenodo](https://zenodo.org/records/11402855). Zenodo record edits are welcome - just let me know.
