### ISSUE TITLE
Determine disposition of content on LC-Overview Index.html page 

### ISSUE THREAD

**Issue by emcaulay** [LibraryCarpentry/lc-overview#57]
### How could the content be improved?

Does any of this content need to be moved to the Library Carpentry website? 

This page will be archived when the LC-Overview Lesson is decommissioned on 2024-03-29.

**Comment by emcaulay** [comment]
@emcaulay and @jt14den discussed in meeting on 2023-11-28, this content seems either duplicative of existing information on the LC website, but it should be reviewed for any tidbits that need copying into other locations.

**Comment by emcaulay** [comment]
Relates to #49.

**Comment by chennesy** [comment]
Lesson is retired and archived on [Zenodo](https://zenodo.org/records/11402855).
