### ISSUE TITLE
LC-Overview Decommission Project - Determine disposition of Episode 2

### ISSUE THREAD

**Issue by emcaulay** [LibraryCarpentry/lc-overview#58]
### How could the content be improved?

Per discussion on #49, and approval of the LC-CAC, the LC-Overview lesson will be decommissioned on 2024-03-29. 

All episodes of the lesson will have their own issue to discuss whether the content should be migrated to a new home or simply archived. 

This issue is about Episode 2, titled "Introduction to Library Carpentry".
https://librarycarpentry.org/lc-overview/02-intro-to-library-carpentry/index.html

Next actions:
1. Re-read the content and see if it is similar to or duplicates any parts of the Library Carpentry website
2. Determine who manages updates and content on the Library Carpentry website (@emcaulay has reached out directly on Carpentries Slack to ask about that on 2023-11-30). 

First proposal:
Move this content to another location focused on sharing information about the Library Carpentry program and not as a lesson (if not already a blog post or article?)

**Comment by jas58** [comment]
I'm interested!

**Comment by chennesy** [comment]
@jas58 Let me know if you have bandwidth to help out with this:

A few of us from the @LibraryCarpentry/curriculum-advisors just met and are hoping to find a volunteer to go through the [Intro to LC episode](https://librarycarpentry.org/lc-overview/02-intro-to-library-carpentry.html) and the [Summary & Setup page](https://librarycarpentry.org/lc-overview/index.html) to see if there is any unique and worthwhile content that is not already available on the [LC website](https://librarycarpentry.org/). The hope is to migrate any content that we want to retain from those two episodes to the LC site (if it's not already there) before we retire LC overview.

@jt14den and I can both help with the actual migration, but first we're hoping to identify what content is worth retaining (if any). Lmk if that's something you're interested in! And no problem if not, we're just going by your "I'm interested" comment :)

**Comment by jas58** [comment]
Hi Cody,
What is the deadline?
My calendar opens up May 12.

Cordially,
Jennifer

**Comment by chennesy** [comment]
That's great, thanks Jennifer! There is no specific deadline, but wrapping it up this summer would be great. We will go ahead and move the LC Overview lesson to the Retired Lessons list on the LC site soon, but will keep the repo up until we've finished migrating content. (Once we're done with that process we'll archive the LC Overview repo). Let me know if you'd like me to set up a meeting for mid-May or have any questions.

**Comment by tobyhodges** [comment]
Hi folks, I recently received an update about the ongoing redesign of the Carpentries website. One of the tasks associated with that is a drive to reduce redundancy between the individual lesson program websites (like https://librarycarpentry.org) and the main Carpentries site (https://carpentries.org), and to increase consistency between the individual LP sites. An implication of this is that the LC site will probably not be a great place to host the _Introduction to Library Carpentry_ episode content in the future.

If you find that there is enough material worth keeping in episode 2, @jas58, my suggestion is to put it into a PDF (e.g. an exported set of slides) and publish those to Zenodo. We can the link to the DOI from wherever it feels most relevant e.g. the Instructor Notes of the first lesson in the LC core curriculum, and from the About Library Carpentry section of the websites.

**Comment by chennesy** [comment]
That's great @tobyhodges, and a much simpler solution for us to move forward. Thanks!

**Comment by chennesy** [comment]
This lesson is now retired and archived [on Zenodo](https://zenodo.org/records/11402855). @jas58: no need to work on this clean-up project, but thanks so much for the offer to help!
